### ISSUE TITLE
Provide a way to easily run the notebooks using MyBinder

### ISSUE THREAD

**Issue by psychemedia** [colinleach/astro-Jupyter#2]
It would be useful to provide a way of running the notebooks in this repo using [MyBinder](https://mybinder.readthedocs.io/en/latest/).

This could be done either by providing a set of requirements (tidily placed in a `binder/` directory, for example) or by providing a link to a repository that builds a suitable environment and then pulls in the notebooks contained in this repository.

To this latter end, I've started trying to identify and include requirements [here](https://github.com/ouseful-demos/binder-base-boxes/tree/astronomy) which can be used to run the notebooks in this repo using a link of the form:

https://mybinder.org/v2/gh/ouseful-demos/binder-base-boxes/astronomy/?urlpath=git-pull?repo=https://github.com/colinleach/astro-Jupyter

**Comment by colinleach** [comment]
An interesting and helpful suggestion - thank you. I've not used MyBinder before so I'll read around it and try to get it running in this repo.

I worry a bit about the length of the requirements. One of the things I've been doing is try out lots of different packages (most of them just used in a single nb), so an environment that can run _every_ notebook might take a long time to build. I'd better experiment and collect real data...

**Comment by psychemedia** [comment]
In the "traditional" MyBinder model, each time you update any file in the repo, even if it's just the README, the next time you try to launch the repo on MyBinder requires the Docker container to be built. As you say, for complex dependencies, this can take a long time.

The joy of using the *`nbgitpuller` in a "base box"* approach is that the base box can be built once and then use `nbgitpuller` to pull the notebooks in from another repo (such as this one). Even if you update your notebooks, there's no need to rebuild the base box, because the contents of the notebook repo are simply being copied in to a Binder environment built from another repo, rather than used to build the Binder environment.

**Comment by colinleach** [comment]
Great, I'll try it that way. I just tried creating a minimal conda environment and the 28 dependencies in my requirements.yml turned into 216 packages once it figured out all the second-level dependencies. Slow!

**Comment by psychemedia** [comment]
You will also need to add `nbgitpuller` as a dependency in the repo you use to define the Binder environment.

**Comment by colinleach** [comment]
This is now mostly working: https://mybinder.org/v2/gh/colinleach/binder-box/master/?urlpath=git-pull?repo=https://github.com/colinleach/astro-Jupyter

Not everything displays correctly, e.g. Bokeh plots fail without an error. Maybe some issue serving the Javascript? Fighting with that isn't my most urgent priority just now.

**Comment by colinleach** [comment]
Don't rush to test it. It's rebuilding the Docker container (new README!) and that takes about 30 mins.

**Comment by psychemedia** [comment]
Looks like quite a comprehensive build and seems to work well :-)

This has also got me thinking... Github uses `gh-pages` as a more or less reserved branchname for building Github Pages sites associated with a particular repo.

Would a convention for `binder-build` branches also be useful?

eg then we'd have something like:

https://mybinder.org/v2/gh/colinleach/astro-Jupyter/binder-build/?urlpath=git-pull?repo=https://github.com/colinleach/astro-Jupyter

If you're pulling from different (conventional) branches of the same repo (`master` for the notebooks and `binder-build` for the base container), then the calling URL could possibly be simplified even further to assume particular defaults...

**Comment by colinleach** [comment]
I can see this could be useful but it's well outside my expertise. Good luck!
